os: linux
dist: xenial
language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.3

android:
  components:
    - tools
    - platform-tools

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;31.0.2"

script:
  - sdkmanager --list
